---
title: "Exercise 5"
author: "Carilli"
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 5data}
height_wages <- 
  here::here("data", "heightwage_british_males_multivariate.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  rename(height_07 = height07, height_16 = height16, height_33 = height33,
         gwage_33 = gwage33, mom_ed = momed, dad_ed = daded, 
         ht_16_noisy = ht16noisy)
```

### (a)

```{r 5a}
height_wages %>% 
  lm(gwage_33 ~ height_33 + height_16, .) %>% 
  jtools::summ()
```

### (b)

```{r 5b}
height_wages %>% 
  lm(gwage_33 ~ height_33 + height_16 + height_07, .) %>% 
  jtools::summ()
```

### (c)

```{r 5c}
height_wages %>% 
  lm(gwage_33 ~ height_33 + height_16 + height_07, .) %>% 
  jtools::summ(vifs = TRUE)
```

### (d)

```{r 5d}
height_wages %>% 
  lm(gwage_33 ~ height_16 + mom_ed + dad_ed, .) %>% 
  jtools::summ()

height_wages %>% 
  lm(gwage_33 ~ height_33 + height_16 + height_07 + mom_ed + dad_ed, .) %>% 
  jtools::summ()
```

### (e)

```{r 5e}
height_wages %$% 
  lm(gwage_33 ~ height_16 + mom_ed + dad_ed + siblings) %>% 
  jtools::summ()
```

### (f)

```{r 5f}
jtools::export_summs(
  height_wages %>% 
  lm(gwage_33 ~ ht_16_noisy + mom_ed + dad_ed + siblings, .),
  
  height_wages %>% 
  lm(gwage_33 ~ height_16 + mom_ed + dad_ed + siblings, .)
)

```

