---
title: "Exercise 2"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 2data}
mlb <- 
here::here("data", "MLBattend.csv") %>% 
  read_csv() %>% 
  janitor::clean_names()

```

### (a)

```{r 2a}
mlb %>% 
  lm(home_attend ~ wins + runs_scored + runs_allowed, .) %>% 
  summary()
```

### (b)

The two conditions are (i) season must affect attendance and (ii) season must be correlated with the independent variables in part (a). Condition (i) is likely true because it makes sense that overall attendance has been rising with population. Condition (ii) is hard to assess, but would hold if it is the case that there are more runs scored over time, for example.

### (c)

```{r 2c}
mlb %>% 
  lm(home_attend ~ wins + runs_scored + runs_allowed + season, .) %>% 
  summary()

jtools::export_summs(
  mlb %>% 
  lm(home_attend ~ wins + runs_scored + runs_allowed, .),
  
  mlb %>% 
  lm(home_attend ~ wins + runs_scored + runs_allowed + season, .)
)
```

### (d)

```{r 2d}
mlb %>% 
  ggplot(aes(x = season, y = runs_scored)) + 
  geom_jitter(width = 0, height = .4, alpha = .3) + 
  xlab("Season") +
  ylab("Runs Scored") +
  geom_smooth(method = "lm", se = FALSE)

mlb %$% 
  lm(runs_scored ~ season) %>% 
  summary()
```


### (e)

```{r 2e}
mlb %>% 
  mutate(across(where(is.numeric), scale)) %>% 
  lm(home_attend ~ wins + runs_scored + runs_allowed + season, .) %>% 
  summary()

mlb %>% 
  mutate(across(where(is.numeric), scale)) %>% 
  lm(home_attend ~ wins + runs_scored + runs_allowed + season, .) %>% 
  jtools::summ(scale = TRUE, transform.response = TRUE)

mlb %>% 
  lm(home_attend ~ wins + runs_scored + runs_allowed + season, .) %>% 
  lm.beta::lm.beta() 
```



